language: python
python:
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq file libmagic1

after_install:
  - file --version

# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors

# command to run tests
script: nosetests tests --with-coverage --cover-inclusive

after_success:
  - coveralls
